# Goal
sensor_msgs/JointState joint_state

---
# Result
bool success
string message

---
# Feedback
float64[] desired_positions
float64[] desired_velocities
float64[] actual_positions
float64[] actual_velocities
